'use client';

import PptxGenJS from 'pptxgenjs';

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

export interface ParsedSlide {
  title: string;
  bullets: string[];
  notes?: string;
}

/* ------------------------------------------------------------------ */
/*  Parse markdown content into individual slides                      */
/* ------------------------------------------------------------------ */

export function parseMarkdownToSlides(content: string): ParsedSlide[] {
  if (!content) return [];

  // Split by ## headings (slide separators)
  const sections = content.split(/^##\s+/gm).filter(Boolean);

  if (sections.length === 0) {
    // Fallback: treat whole content as one slide
    return [{
      title: 'Slide 1',
      bullets: content.split('\n').filter(l => l.trim()),
    }];
  }

  return sections.map((section) => {
    const lines = section.split('\n');
    const title = lines[0]?.trim() || 'Untitled Slide';
    const bodyLines = lines.slice(1).filter(l => l.trim());

    const bullets: string[] = [];
    for (const line of bodyLines) {
      // Remove markdown bullet markers
      const cleaned = line
        .replace(/^[-*•]\s+/, '')
        .replace(/^\d+\.\s+/, '')
        .replace(/\*\*(.*?)\*\*/g, '$1')   // bold
        .replace(/\*(.*?)\*/g, '$1')        // italic
        .replace(/`(.*?)`/g, '$1')          // inline code
        .replace(/\[(.*?)\]\(.*?\)/g, '$1') // links
        .trim();
      if (cleaned) bullets.push(cleaned);
    }

    return { title, bullets };
  });
}

/* ------------------------------------------------------------------ */
/*  Brand constants                                                    */
/* ------------------------------------------------------------------ */

const BRAND = {
  darkBg: '0F0F0F',
  cardBg: '1A1A1A',
  yellow: 'FEC00F',
  turquoise: '00DED1',
  white: 'FFFFFF',
  lightGray: 'B0B0B0',
  darkGray: '222222',
  fontTitle: 'Rajdhani',
  fontBody: 'Quicksand',
} as const;

/* ------------------------------------------------------------------ */
/*  Generate PPTX from parsed slides                                   */
/* ------------------------------------------------------------------ */

export async function generatePptx(
  title: string,
  slides: ParsedSlide[],
): Promise<Blob> {
  const pptx = new PptxGenJS();

  // Presentation metadata
  pptx.author = 'Potomac Analyst Workbench';
  pptx.company = 'Potomac Asset Management';
  pptx.title = title;
  pptx.layout = 'LAYOUT_WIDE'; // 13.33 x 7.5

  // Define slide master
  pptx.defineSlideMaster({
    title: 'POTOMAC_DARK',
    background: { color: BRAND.darkBg },
    objects: [
      // Bottom accent bar
      {
        rect: {
          x: 0, y: 6.95, w: '100%', h: 0.55,
          fill: { color: BRAND.cardBg },
        },
      },
      // Yellow accent line
      {
        rect: {
          x: 0, y: 6.93, w: '100%', h: 0.03,
          fill: { color: BRAND.yellow },
        },
      },
      // Footer text
      {
        text: {
          text: 'POTOMAC ASSET MANAGEMENT',
          options: {
            x: 0.5, y: 7.05, w: 5, h: 0.35,
            fontSize: 8, fontFace: BRAND.fontTitle,
            color: BRAND.lightGray, bold: true,
            charSpacing: 2,
          },
        },
      },
      // Slide number
      {
        text: {
          text: '{{slideNumber}}',
          options: {
            x: 11.5, y: 7.05, w: 1.5, h: 0.35,
            fontSize: 8, fontFace: BRAND.fontBody,
            color: BRAND.lightGray, align: 'right',
          },
        },
      },
    ],
  });

  // --- TITLE SLIDE ---
  const titleSlide = pptx.addSlide({ masterName: 'POTOMAC_DARK' });

  // Gradient-style accent block at top
  titleSlide.addShape('rect' as PptxGenJS.ShapeType, {
    x: 0, y: 0, w: '100%', h: 0.06,
    fill: { color: BRAND.yellow },
  });

  titleSlide.addText(title.toUpperCase(), {
    x: 0.8, y: 1.8, w: 11.7, h: 1.5,
    fontSize: 36, fontFace: BRAND.fontTitle,
    color: BRAND.white, bold: true,
    charSpacing: 3, lineSpacing: 42,
  });

  titleSlide.addText('Generated by Potomac Analyst Workbench', {
    x: 0.8, y: 3.4, w: 11.7, h: 0.5,
    fontSize: 13, fontFace: BRAND.fontBody,
    color: BRAND.lightGray,
  });

  // Yellow divider line
  titleSlide.addShape('rect' as PptxGenJS.ShapeType, {
    x: 0.8, y: 4.1, w: 2.5, h: 0.04,
    fill: { color: BRAND.yellow },
  });

  const dateStr = new Date().toLocaleDateString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric',
  });
  titleSlide.addText(dateStr, {
    x: 0.8, y: 4.3, w: 11.7, h: 0.4,
    fontSize: 11, fontFace: BRAND.fontBody,
    color: BRAND.lightGray,
  });

  // --- CONTENT SLIDES ---
  for (const slide of slides) {
    const s = pptx.addSlide({ masterName: 'POTOMAC_DARK' });

    // Yellow accent bar on left edge
    s.addShape('rect' as PptxGenJS.ShapeType, {
      x: 0, y: 0, w: 0.06, h: '100%',
      fill: { color: BRAND.yellow },
    });

    // Slide title
    s.addText(slide.title.toUpperCase(), {
      x: 0.8, y: 0.4, w: 11.7, h: 0.8,
      fontSize: 22, fontFace: BRAND.fontTitle,
      color: BRAND.yellow, bold: true,
      charSpacing: 2,
    });

    // Divider
    s.addShape('rect' as PptxGenJS.ShapeType, {
      x: 0.8, y: 1.25, w: 11.7, h: 0.015,
      fill: { color: '333333' },
    });

    // Bullet content
    if (slide.bullets.length > 0) {
      const bulletRows: PptxGenJS.TextProps[] = slide.bullets.map(b => ({
        text: b,
        options: {
          fontSize: 14,
          fontFace: BRAND.fontBody,
          color: BRAND.white,
          bullet: { code: '25CF', color: BRAND.yellow } as never,
          lineSpacing: 26,
          paraSpaceBefore: 4,
          paraSpaceAfter: 4,
          indentLevel: 0,
        },
      }));

      s.addText(bulletRows, {
        x: 0.8, y: 1.5, w: 11.7, h: 5.2,
        valign: 'top',
      });
    }
  }

  // Generate blob
  const output = await pptx.write({ outputType: 'blob' });
  return output as Blob;
}

/* ------------------------------------------------------------------ */
/*  Convenience: markdown → download .pptx                             */
/* ------------------------------------------------------------------ */

export async function downloadSlidesAsPptx(title: string, content: string): Promise<void> {
  const slides = parseMarkdownToSlides(content);
  const blob = await generatePptx(title, slides);

  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${title.replace(/[^a-zA-Z0-9 ]/g, '').trim()}.pptx`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
