name: "AFL_Code_Generator"
version: "1.0.0"
description: "Generates optimized AmiBroker AFL code from natural language descriptions"
category: "Trading"
tags: ["AFL", "AmiBroker", "Code Generation", "Trading Strategies"]

input_schema:
  type: "object"
  properties:
    description:
      type: "string"
      description: "Natural language description of the trading strategy"
      minLength: 10
    strategy_type:
      type: "string"
      enum: ["standalone", "composite", "indicator", "scan"]
      default: "standalone"
    complexity:
      type: "string"
      enum: ["basic", "intermediate", "advanced"]
      default: "intermediate"
    include_optimization:
      type: "boolean"
      default: false
      description: "Whether to include optimization parameters"
    include_comments:
      type: "boolean"
      default: true
      description: "Whether to include explanatory comments"
    timeframe:
      type: "string"
      enum: ["intraday", "daily", "weekly", "monthly"]
      default: "daily"
      description: "Target timeframe for the strategy"

output_schema:
  type: "object"
  properties:
    afl_code:
      type: "string"
      description: "Generated AFL code"
    explanation:
      type: "string"
      description: "Plain English explanation of the strategy"
    parameters:
      type: "array"
      items: {"type": "object"}
      description: "Suggested optimization parameters"
    validation:
      type: "object"
      properties:
        syntax_valid: {"type": "boolean"}
        best_practices: {"type": "array", "items": {"type": "string"}}
        optimization_ready: {"type": "boolean"}
    complexity_score:
      type: "number"
      minimum: 1
      maximum: 10
      description: "Complexity score of generated code"

required: ["afl_code", "explanation", "validation"]

triggers:
  - "generate afl code"
  - "create trading strategy"
  - "build indicator"
  - "write afl script"
  - "develop trading algorithm"

dependencies:
  - "Syntax Keywords"
  - "Common Mistakes"
  - "Param Optimize Standard"

execution_flow:
  parallel: false
  error_handling: "continue_on_error"
  result_aggregation: "single_result"

performance_optimizations:
  context_truncation: true
  token_limit: 4000
  caching_enabled: true
  parallel_processing: false

optimization_settings:
  max_execution_time: "30s"
  memory_limit: "256MB"
  concurrent_requests: 5