import { tool as createTool } from 'ai';
import { z } from 'zod';

// AFL Code Generation Tool
export const aflGeneratorTool = createTool({
  description: 'Generate AFL (AmiBroker Formula Language) code for trading strategies',
  inputSchema: z.object({
    strategy: z.string().describe('The trading strategy to implement'),
    indicators: z.array(z.string()).optional().describe('Technical indicators to use'),
    timeframe: z.string().optional().describe('Trading timeframe'),
  }),
  execute: async function ({ strategy, indicators, timeframe }) {
    // Simulate AFL code generation
    await new Promise(resolve => setTimeout(resolve, 1000));
    
    const code = `// AFL Strategy: ${strategy}
// Timeframe: ${timeframe || 'Daily'}
// Generated by Analyst AI

_SECTION_BEGIN("${strategy}");

// Parameters
period = Param("Period", 14, 5, 50, 1);

// Indicators
${indicators?.includes('RSI') ? 'rsi_value = RSI(period);' : ''}
${indicators?.includes('MACD') ? 'macd_line = MACD(12, 26);\nsignal_line = Signal(12, 26, 9);' : ''}
${indicators?.includes('MA') ? 'ma_short = MA(Close, 20);\nma_long = MA(Close, 50);' : ''}

// Entry Conditions
Buy = Cross(ma_short, ma_long);
Sell = Cross(ma_long, ma_short);

// Position Sizing
SetPositionSize(10, spsPercentOfEquity);

// Plot
Plot(Close, "Price", colorBlack, styleCandle);
${indicators?.includes('MA') ? 'Plot(ma_short, "MA20", colorGreen, styleLine);\nPlot(ma_long, "MA50", colorRed, styleLine);' : ''}

_SECTION_END();`;

    return {
      code,
      language: 'afl',
      strategy,
      timeframe: timeframe || 'Daily',
    };
  },
});

// Mermaid Diagram Tool
export const mermaidDiagramTool = createTool({
  description: 'Generate Mermaid diagrams for visualizing trading strategies and workflows',
  inputSchema: z.object({
    type: z.enum(['flowchart', 'sequence', 'gantt', 'pie']).describe('Type of diagram'),
    title: z.string().describe('Title of the diagram'),
    content: z.string().describe('Content to visualize'),
  }),
  execute: async function ({ type, title, content }) {
    await new Promise(resolve => setTimeout(resolve, 500));
    
    let diagram = '';
    
    switch (type) {
      case 'flowchart':
        diagram = `flowchart TD
    A[${title}] --> B[Analyze Market]
    B --> C{Signal Generated?}
    C -->|Yes| D[Execute Trade]
    C -->|No| E[Wait]
    D --> F[Monitor Position]
    F --> G{Exit Signal?}
    G -->|Yes| H[Close Position]
    G -->|No| F
    H --> I[Record Results]`;
        break;
      
      case 'sequence':
        diagram = `sequenceDiagram
    participant User
    participant System
    participant Market
    
    User->>System: ${title}
    System->>Market: Analyze Data
    Market-->>System: Return Signals
    System-->>User: Display Results`;
        break;
      
      default:
        diagram = `graph LR
    A[${title}] --> B[${content}]`;
    }
    
    return {
      code: diagram,
      language: 'mermaid',
      type,
    };
  },
});

// React Chart Component Tool
export const chartComponentTool = createTool({
  description: 'Generate React components with Recharts for data visualization',
  inputSchema: z.object({
    chartType: z.enum(['line', 'bar', 'area', 'pie', 'composed']).describe('Type of chart'),
    title: z.string().describe('Chart title'),
    dataPoints: z.number().optional().default(10).describe('Number of data points'),
  }),
  execute: async function ({ chartType, title, dataPoints }) {
    await new Promise(resolve => setTimeout(resolve, 800));
    
    // Generate sample data
    const data = Array.from({ length: dataPoints }, (_, i) => ({
      name: `Day ${i + 1}`,
      value: Math.floor(Math.random() * 100) + 50,
      volume: Math.floor(Math.random() * 1000) + 500,
    }));
    
    let chartCode = '';
    
    switch (chartType) {
      case 'line':
        chartCode = `
  <ResponsiveContainer width="100%" height={400}>
    <LineChart data={data}>
      <CartesianGrid strokeDasharray="3 3" />
      <XAxis dataKey="name" />
      <YAxis />
      <Tooltip />
      <Legend />
      <Line type="monotone" dataKey="value" stroke="#8884d8" />
      <Line type="monotone" dataKey="volume" stroke="#82ca9d" />
    </LineChart>
  </ResponsiveContainer>`;
        break;
      
      case 'bar':
        chartCode = `
  <ResponsiveContainer width="100%" height={400}>
    <BarChart data={data}>
      <CartesianGrid strokeDasharray="3 3" />
      <XAxis dataKey="name" />
      <YAxis />
      <Tooltip />
      <Legend />
      <Bar dataKey="value" fill="#8884d8" />
      <Bar dataKey="volume" fill="#82ca9d" />
    </BarChart>
  </ResponsiveContainer>`;
        break;
      
      case 'area':
        chartCode = `
  <ResponsiveContainer width="100%" height={400}>
    <AreaChart data={data}>
      <CartesianGrid strokeDasharray="3 3" />
      <XAxis dataKey="name" />
      <YAxis />
      <Tooltip />
      <Legend />
      <Area type="monotone" dataKey="value" stackId="1" stroke="#8884d8" fill="#8884d8" />
      <Area type="monotone" dataKey="volume" stackId="1" stroke="#82ca9d" fill="#82ca9d" />
    </AreaChart>
  </ResponsiveContainer>`;
        break;
      
      default:
        chartCode = `
  <ResponsiveContainer width="100%" height={400}>
    <LineChart data={data}>
      <CartesianGrid strokeDasharray="3 3" />
      <XAxis dataKey="name" />
      <YAxis />
      <Tooltip />
      <Legend />
      <Line type="monotone" dataKey="value" stroke="#8884d8" />
    </LineChart>
  </ResponsiveContainer>`;
    }
    
    const code = `import React from 'react';
import { ${chartType === 'line' ? 'LineChart, Line' : chartType === 'bar' ? 'BarChart, Bar' : 'AreaChart, Area'}, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';

const ${title.replace(/\s+/g, '')}Chart = () => {
  const data = ${JSON.stringify(data, null, 2)};
  
  return (
    <div style={{ padding: '20px' }}>
      <h2 style={{ marginBottom: '20px', color: '#333' }}>${title}</h2>
      ${chartCode}
    </div>
  );
};

export default ${title.replace(/\s+/g, '')}Chart;`;
    
    return {
      code,
      language: 'jsx',
      id: `chart-${Date.now()}`,
    };
  },
});

// Backtest Results Tool
export const backtestResultsTool = createTool({
  description: 'Display backtest results and performance metrics',
  inputSchema: z.object({
    strategy: z.string().describe('Strategy name'),
    metrics: z.object({
      totalReturn: z.number().describe('Total return percentage'),
      winRate: z.number().describe('Win rate percentage'),
      sharpeRatio: z.number().describe('Sharpe ratio'),
      maxDrawdown: z.number().describe('Maximum drawdown percentage'),
      totalTrades: z.number().describe('Total number of trades'),
    }),
  }),
  execute: async function ({ strategy, metrics }) {
    await new Promise(resolve => setTimeout(resolve, 600));
    
    const code = `import React from 'react';

const BacktestResults = () => {
  const metrics = ${JSON.stringify(metrics, null, 2)};
  
  const getColorForMetric = (value, type) => {
    switch(type) {
      case 'return':
      case 'winRate':
      case 'sharpe':
        return value > 0 ? '#22c55e' : '#ef4444';
      case 'drawdown':
        return value < -20 ? '#ef4444' : value < -10 ? '#f59e0b' : '#22c55e';
      default:
        return '#6b7280';
    }
  };
  
  return (
    <div style={{
      padding: '24px',
      backgroundColor: '#f9fafb',
      borderRadius: '12px',
      border: '1px solid #e5e7eb',
    }}>
      <h2 style={{ marginBottom: '20px', color: '#111827', fontSize: '24px', fontWeight: 'bold' }}>
        Backtest Results: ${strategy}
      </h2>
      
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
        gap: '16px',
      }}>
        <div style={{
          padding: '16px',
          backgroundColor: 'white',
          borderRadius: '8px',
          border: '1px solid #e5e7eb',
        }}>
          <div style={{ fontSize: '14px', color: '#6b7280', marginBottom: '4px' }}>Total Return</div>
          <div style={{ 
            fontSize: '24px', 
            fontWeight: 'bold',
            color: getColorForMetric(metrics.totalReturn, 'return')
          }}>
            {metrics.totalReturn.toFixed(2)}%
          </div>
        </div>
        
        <div style={{
          padding: '16px',
          backgroundColor: 'white',
          borderRadius: '8px',
          border: '1px solid #e5e7eb',
        }}>
          <div style={{ fontSize: '14px', color: '#6b7280', marginBottom: '4px' }}>Win Rate</div>
          <div style={{ 
            fontSize: '24px', 
            fontWeight: 'bold',
            color: getColorForMetric(metrics.winRate, 'winRate')
          }}>
            {metrics.winRate.toFixed(1)}%
          </div>
        </div>
        
        <div style={{
          padding: '16px',
          backgroundColor: 'white',
          borderRadius: '8px',
          border: '1px solid #e5e7eb',
        }}>
          <div style={{ fontSize: '14px', color: '#6b7280', marginBottom: '4px' }}>Sharpe Ratio</div>
          <div style={{ 
            fontSize: '24px', 
            fontWeight: 'bold',
            color: getColorForMetric(metrics.sharpeRatio, 'sharpe')
          }}>
            {metrics.sharpeRatio.toFixed(2)}
          </div>
        </div>
        
        <div style={{
          padding: '16px',
          backgroundColor: 'white',
          borderRadius: '8px',
          border: '1px solid #e5e7eb',
        }}>
          <div style={{ fontSize: '14px', color: '#6b7280', marginBottom: '4px' }}>Max Drawdown</div>
          <div style={{ 
            fontSize: '24px', 
            fontWeight: 'bold',
            color: getColorForMetric(metrics.maxDrawdown, 'drawdown')
          }}>
            {metrics.maxDrawdown.toFixed(2)}%
          </div>
        </div>
        
        <div style={{
          padding: '16px',
          backgroundColor: 'white',
          borderRadius: '8px',
          border: '1px solid #e5e7eb',
        }}>
          <div style={{ fontSize: '14px', color: '#6b7280', marginBottom: '4px' }}>Total Trades</div>
          <div style={{ fontSize: '24px', fontWeight: 'bold', color: '#111827' }}>
            {metrics.totalTrades}
          </div>
        </div>
      </div>
    </div>
  );
};

export default BacktestResults;`;
    
    return {
      code,
      language: 'jsx',
      id: `backtest-${Date.now()}`,
      strategy,
      metrics,
    };
  },
});

// Technical Indicator Tool
export const technicalIndicatorTool = createTool({
  description: 'Calculate and display technical indicators',
  inputSchema: z.object({
    indicator: z.enum(['RSI', 'MACD', 'BollingerBands', 'SMA', 'EMA']).describe('Technical indicator type'),
    symbol: z.string().describe('Stock symbol'),
    period: z.number().optional().default(14).describe('Period for calculation'),
  }),
  execute: async function ({ indicator, symbol, period }) {
    await new Promise(resolve => setTimeout(resolve, 700));
    
    // Generate sample indicator values
    const values = Array.from({ length: 20 }, (_, i) => ({
      date: `2024-01-${String(i + 1).padStart(2, '0')}`,
      value: 50 + Math.sin(i / 3) * 20 + Math.random() * 10,
    }));
    
    const code = `import React from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, ReferenceLine } from 'recharts';

const ${indicator}Indicator = () => {
  const data = ${JSON.stringify(values, null, 2)};
  
  const getIndicatorColor = (value) => {
    if ('${indicator}' === 'RSI') {
      if (value > 70) return '#ef4444'; // Overbought
      if (value < 30) return '#22c55e'; // Oversold
      return '#3b82f6'; // Neutral
    }
    return '#8884d8';
  };
  
  return (
    <div style={{ padding: '20px' }}>
      <h3 style={{ marginBottom: '16px', color: '#333' }}>
        ${indicator} Indicator - ${symbol} (Period: ${period})
      </h3>
      
      <ResponsiveContainer width="100%" height={300}>
        <LineChart data={data}>
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="date" />
          <YAxis domain={${indicator === 'RSI' ? '[0, 100]' : '["auto", "auto"]'}} />
          <Tooltip />
          <Legend />
          ${indicator === 'RSI' ? `
          <ReferenceLine y={70} stroke="#ef4444" strokeDasharray="5 5" label="Overbought" />
          <ReferenceLine y={30} stroke="#22c55e" strokeDasharray="5 5" label="Oversold" />
          ` : ''}
          <Line 
            type="monotone" 
            dataKey="value" 
            stroke="#8884d8" 
            name="${indicator}"
            strokeWidth={2}
          />
        </LineChart>
      </ResponsiveContainer>
      
      <div style={{ marginTop: '16px', padding: '12px', backgroundColor: '#f3f4f6', borderRadius: '8px' }}>
        <p style={{ fontSize: '14px', color: '#6b7280' }}>
          ${indicator === 'RSI' ? 'RSI measures momentum. Values above 70 indicate overbought conditions, below 30 indicate oversold.' :
            indicator === 'MACD' ? 'MACD is a trend-following momentum indicator showing the relationship between two moving averages.' :
            indicator === 'BollingerBands' ? 'Bollinger Bands measure volatility and provide relative definitions of high and low prices.' :
            `${indicator} is a technical indicator used to analyze price trends.`}
        </p>
      </div>
    </div>
  );
};

export default ${indicator}Indicator;`;
    
    return {
      code,
      language: 'jsx',
      id: `indicator-${Date.now()}`,
      indicator,
      symbol,
    };
  },
});

// Weather Tool
export const weatherTool = createTool({
  description: 'Display the weather for a location',
  inputSchema: z.object({
    location: z.string().describe('The location to get the weather for'),
  }),
  execute: async function ({ location }) {
    // Simulate weather API call
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    // Generate realistic weather data
    const conditions = ['Sunny', 'Partly Cloudy', 'Cloudy', 'Rainy', 'Stormy'];
    const condition = conditions[Math.floor(Math.random() * conditions.length)];
    const temperature = Math.floor(Math.random() * 30) + 60; // 60-90°F
    const humidity = Math.floor(Math.random() * 40) + 40; // 40-80%
    const windSpeed = Math.floor(Math.random() * 20) + 5; // 5-25 mph
    
    return { 
      weather: condition, 
      temperature, 
      location,
      humidity,
      windSpeed,
      forecast: [
        { day: 'Tomorrow', high: temperature + 5, low: temperature - 5, condition: 'Partly Cloudy' },
        { day: 'Day After', high: temperature + 3, low: temperature - 3, condition: 'Sunny' },
      ]
    };
  },
});

// Export all tools
export const tools = {
  displayWeather: weatherTool,
  generateAFL: aflGeneratorTool,
  createDiagram: mermaidDiagramTool,
  createChart: chartComponentTool,
  showBacktest: backtestResultsTool,
  calculateIndicator: technicalIndicatorTool,
};
