'use client';

import React, { useState, useMemo, useEffect, useCallback, useRef } from 'react';
import {
  ChevronLeft, ChevronRight, Maximize2, Minimize2,
  Download, Grid, Layers, Play, X, StickyNote,
  ImageIcon, Columns2, Quote, Minus, AlignCenter,
} from 'lucide-react';
import { parseMarkdownToSlides, downloadSlidesAsPptx, type ParsedSlide } from '@/lib/pptxExport';
import { useResponsive } from '@/hooks/useResponsive';
import type { SlideLayout, ThemeColors } from './SlideEditor';

/* ------------------------------------------------------------------ */
/*  Theme (matches SlideEditor defaults for preview consistency)        */
/* ------------------------------------------------------------------ */

const DEFAULT_THEME: ThemeColors = {
  bg: '#0F0F0F', cardBg: '#1A1A1A', accent: '#FEC00F', accentSecondary: '#00DED1',
  titleColor: '#FEC00F', bodyColor: '#E0E0E0', mutedColor: '#666',
  footerBg: '#1A1A1A', footerText: '#666', label: 'Potomac Dark',
};

/* ------------------------------------------------------------------ */
/*  Props                                                              */
/* ------------------------------------------------------------------ */

interface SlidePreviewProps {
  title: string;
  content: string;
  colors: Record<string, string>;
  isDark: boolean;
}

/* ------------------------------------------------------------------ */
/*  Slide Renderer (layout-aware)                                      */
/* ------------------------------------------------------------------ */

function SlideRenderer({ slide, slideIndex, totalSlides, title, t, scale }: {
  slide: ParsedSlide; slideIndex: number; totalSlides: number;
  title: string; t: ThemeColors; scale?: number;
}) {
  const isTitle = slideIndex === 0 && totalSlides > 1;
  const layout: SlideLayout = (slide as ParsedSlide & { layout?: SlideLayout }).layout || 'title-bullets';

  const footer = (
    <div style={{
      height: '32px', flexShrink: 0, borderTop: `2px solid ${t.accent}`,
      backgroundColor: t.footerBg,
      display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 20px',
    }}>
      <span style={{ fontFamily: "'Rajdhani', sans-serif", fontSize: '9px', fontWeight: 700, color: t.footerText, letterSpacing: '2px' }}>
        POTOMAC ASSET MANAGEMENT
      </span>
      <span style={{ fontFamily: "'Quicksand', sans-serif", fontSize: '9px', color: t.footerText }}>
        {slideIndex + 1}
      </span>
    </div>
  );

  // Title Slide (always first)
  if (isTitle) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', backgroundColor: t.bg }}>
        <div style={{ height: '4px', backgroundColor: t.accent, flexShrink: 0 }} />
        <div style={{ flex: 1, padding: '40px 48px', display: 'flex', flexDirection: 'column', justifyContent: 'center', overflow: 'hidden' }}>
          <h1 style={{
            fontFamily: "'Rajdhani', sans-serif", fontWeight: 700,
            fontSize: 'clamp(20px, 3vw, 32px)', color: '#FFFFFF',
            letterSpacing: '2px', textTransform: 'uppercase', margin: '0 0 12px', lineHeight: 1.2,
          }}>{title}</h1>
          <p style={{ fontFamily: "'Quicksand', sans-serif", fontSize: 'clamp(11px, 1.4vw, 14px)', color: '#888', margin: '0 0 16px' }}>
            Generated by Potomac Analyst Workbench
          </p>
          <div style={{ width: '60px', height: '3px', backgroundColor: t.accent, margin: '0 0 12px', borderRadius: '2px' }} />
          <p style={{ fontFamily: "'Quicksand', sans-serif", fontSize: 'clamp(10px, 1.2vw, 12px)', color: t.mutedColor, margin: 0 }}>
            {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </p>
        </div>
        {footer}
      </div>
    );
  }

  // -- Title Only --
  if (layout === 'title-only') {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', backgroundColor: t.bg }}>
        <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '24px 36px' }}>
          <h2 style={{
            fontFamily: "'Rajdhani', sans-serif", fontWeight: 700,
            fontSize: 'clamp(20px, 2.8vw, 28px)', color: t.titleColor,
            letterSpacing: '2px', textTransform: 'uppercase', textAlign: 'center', margin: 0,
          }}>{slide.title}</h2>
        </div>
        {footer}
      </div>
    );
  }

  // -- Section Divider --
  if (layout === 'section-divider') {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', background: `linear-gradient(135deg, ${t.accent}22, ${t.bg})`, backgroundColor: t.bg }}>
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '24px 48px' }}>
          <div style={{ width: '60px', height: '3px', backgroundColor: t.accent, borderRadius: '2px', marginBottom: '16px' }} />
          <h2 style={{
            fontFamily: "'Rajdhani', sans-serif", fontWeight: 700,
            fontSize: 'clamp(22px, 3vw, 32px)', color: t.titleColor,
            letterSpacing: '3px', textTransform: 'uppercase', textAlign: 'center', margin: 0,
          }}>{slide.title}</h2>
          {slide.bullets[0]?.trim() && (
            <p style={{ fontFamily: "'Quicksand', sans-serif", fontSize: 'clamp(11px, 1.2vw, 13px)', color: t.mutedColor, marginTop: '12px', textAlign: 'center' }}>{slide.bullets[0]}</p>
          )}
        </div>
        {footer}
      </div>
    );
  }

  // -- Quote --
  if (layout === 'quote') {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', backgroundColor: t.bg }}>
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '24px 48px' }}>
          <span style={{ fontSize: '48px', color: t.accent, fontFamily: 'Georgia, serif', lineHeight: 1, marginBottom: '4px', opacity: 0.5 }}>{'\u201C'}</span>
          <p style={{
            fontFamily: "'Quicksand', sans-serif", fontSize: 'clamp(14px, 1.8vw, 18px)',
            color: t.bodyColor, textAlign: 'center', lineHeight: 1.8, fontStyle: 'italic', maxWidth: '80%', margin: '0 0 8px',
          }}>{slide.bullets[0] || slide.title}</p>
          {slide.bullets[1]?.trim() && (
            <p style={{ fontFamily: "'Rajdhani', sans-serif", fontSize: '12px', fontWeight: 600, color: t.accent, letterSpacing: '1px', textTransform: 'uppercase', margin: 0 }}>
              {'\u2014 '}{slide.bullets[1]}
            </p>
          )}
        </div>
        {footer}
      </div>
    );
  }

  // -- Image Left --
  if (layout === 'image-left') {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', backgroundColor: t.bg }}>
        <div style={{ flex: 1, display: 'flex', overflow: 'hidden' }}>
          <div style={{ width: '40%', backgroundColor: `${t.accent}10`, display: 'flex', alignItems: 'center', justifyContent: 'center', borderRight: `1px solid ${t.accent}20` }}>
            <div style={{ textAlign: 'center', color: t.mutedColor }}>
              <ImageIcon size={32} style={{ opacity: 0.3 }} />
              <div style={{ fontSize: '9px', fontFamily: "'Quicksand', sans-serif", marginTop: '6px', opacity: 0.5 }}>Image area</div>
            </div>
          </div>
          <div style={{ flex: 1, padding: '20px 24px', display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
            <h2 style={{
              fontFamily: "'Rajdhani', sans-serif", fontWeight: 700,
              fontSize: 'clamp(14px, 1.8vw, 18px)', color: t.titleColor,
              letterSpacing: '1.5px', textTransform: 'uppercase', margin: '0 0 12px',
            }}>{slide.title}</h2>
            {renderBullets(slide.bullets, t)}
          </div>
        </div>
        {footer}
      </div>
    );
  }

  // -- Two Columns --
  if (layout === 'two-columns') {
    const mid = Math.ceil(slide.bullets.length / 2);
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', backgroundColor: t.bg }}>
        <div style={{ position: 'absolute', left: 0, top: 0, bottom: 0, width: '4px', backgroundColor: t.accent }} />
        <div style={{ flex: 1, padding: '20px 32px 20px 20px', overflow: 'auto' }}>
          <h2 style={{
            fontFamily: "'Rajdhani', sans-serif", fontWeight: 700,
            fontSize: 'clamp(14px, 2vw, 20px)', color: t.titleColor,
            letterSpacing: '1.5px', textTransform: 'uppercase', margin: '0 0 8px', paddingLeft: '12px',
          }}>{slide.title}</h2>
          <div style={{ height: '1px', backgroundColor: `${t.accent}30`, margin: '0 0 14px 12px' }} />
          <div style={{ display: 'flex', gap: '20px', paddingLeft: '12px' }}>
            <div style={{ flex: 1 }}>{renderBullets(slide.bullets.slice(0, mid), t)}</div>
            <div style={{ flex: 1 }}>{renderBullets(slide.bullets.slice(mid), t)}</div>
          </div>
        </div>
        {footer}
      </div>
    );
  }

  // -- Full Image --
  if (layout === 'full-image') {
    const mediaUrl = (slide as ParsedSlide & { mediaUrl?: string }).mediaUrl;
    const mediaCaption = (slide as ParsedSlide & { mediaCaption?: string }).mediaCaption;
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', backgroundColor: t.bg }}>
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', position: 'relative' }}>
          {mediaUrl ? (
            <div style={{ flex: 1, backgroundImage: `url(${mediaUrl})`, backgroundSize: 'cover', backgroundPosition: 'center' }}>
              <div style={{ position: 'absolute', inset: 0, background: `linear-gradient(to top, ${t.bg}CC, transparent 50%)` }} />
            </div>
          ) : (
            <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', backgroundColor: `${t.accent}06` }}>
              <div style={{ textAlign: 'center', color: t.mutedColor }}>
                <ImageIcon size={48} style={{ opacity: 0.15 }} />
                <div style={{ fontSize: '11px', fontFamily: "'Quicksand', sans-serif", marginTop: '8px', opacity: 0.4 }}>Full-bleed image</div>
              </div>
            </div>
          )}
          <div style={{ position: 'absolute', bottom: '44px', left: '28px', right: '28px', zIndex: 1 }}>
            <h2 style={{
              fontFamily: "'Rajdhani', sans-serif", fontWeight: 700,
              fontSize: 'clamp(18px, 2.4vw, 24px)', color: '#FFFFFF',
              letterSpacing: '1.5px', textTransform: 'uppercase', margin: '0 0 4px',
              textShadow: '0 2px 8px rgba(0,0,0,0.6)',
            }}>{slide.title}</h2>
            {mediaCaption && (
              <p style={{
                fontFamily: "'Quicksand', sans-serif", fontSize: 'clamp(10px, 1.2vw, 12px)',
                color: '#FFFFFF', opacity: 0.7, margin: 0,
                textShadow: '0 1px 4px rgba(0,0,0,0.5)',
              }}>{mediaCaption}</p>
            )}
          </div>
        </div>
        {footer}
      </div>
    );
  }

  // -- Image Grid --
  if (layout === 'image-grid') {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', backgroundColor: t.bg }}>
        <div style={{ padding: '16px 20px 8px' }}>
          <h2 style={{
            fontFamily: "'Rajdhani', sans-serif", fontWeight: 700,
            fontSize: 'clamp(14px, 1.8vw, 18px)', color: t.titleColor,
            letterSpacing: '1.5px', textTransform: 'uppercase', margin: 0,
          }}>{slide.title}</h2>
        </div>
        <div style={{ flex: 1, display: 'grid', gridTemplateColumns: '1fr 1fr', gridTemplateRows: '1fr 1fr', gap: '6px', padding: '6px 20px 10px' }}>
          {[1, 2, 3, 4].map(i => (
            <div key={i} style={{
              backgroundColor: `${t.accent}06`, borderRadius: '6px',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              border: `1px dashed ${t.accent}15`,
            }}>
              <div style={{ textAlign: 'center', color: t.mutedColor }}>
                <ImageIcon size={20} style={{ opacity: 0.15 }} />
                <div style={{ fontSize: '8px', fontFamily: "'Quicksand', sans-serif", marginTop: '3px', opacity: 0.3 }}>Image {i}</div>
              </div>
            </div>
          ))}
        </div>
        {footer}
      </div>
    );
  }

  // -- Video Embed --
  if (layout === 'video-embed') {
    const mediaUrl = (slide as ParsedSlide & { mediaUrl?: string }).mediaUrl;
    const mediaCaption = (slide as ParsedSlide & { mediaCaption?: string }).mediaCaption;
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', backgroundColor: t.bg }}>
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '20px 32px' }}>
          <div style={{
            width: '80%', aspectRatio: '16/9', backgroundColor: `${t.accent}06`,
            borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center',
            border: `1px dashed ${t.accent}15`, position: 'relative', overflow: 'hidden',
          }}>
            <div style={{
              width: '48px', height: '48px', borderRadius: '50%',
              backgroundColor: `${t.accent}25`, display: 'flex',
              alignItems: 'center', justifyContent: 'center',
              transition: 'transform 0.2s ease',
            }}>
              <div style={{
                width: 0, height: 0,
                borderLeft: `16px solid ${t.accent}`, borderTop: '10px solid transparent',
                borderBottom: '10px solid transparent', marginLeft: '4px',
              }} />
            </div>
            {mediaUrl && (
              <div style={{
                position: 'absolute', bottom: '8px', left: '10px', right: '10px',
                backgroundColor: 'rgba(0,0,0,0.7)', borderRadius: '6px', padding: '5px 10px',
              }}>
                <span style={{
                  fontFamily: "'Quicksand', sans-serif", fontSize: '8px', color: '#999',
                  overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', display: 'block',
                }}>{mediaUrl}</span>
              </div>
            )}
          </div>
          <h2 style={{
            fontFamily: "'Rajdhani', sans-serif", fontWeight: 700,
            fontSize: 'clamp(14px, 1.8vw, 18px)', color: t.titleColor,
            letterSpacing: '1.5px', textTransform: 'uppercase', margin: '14px 0 4px', textAlign: 'center',
          }}>{slide.title}</h2>
          {mediaCaption && (
            <p style={{
              fontFamily: "'Quicksand', sans-serif", fontSize: 'clamp(10px, 1.2vw, 12px)',
              color: t.mutedColor, textAlign: 'center', margin: 0,
            }}>{mediaCaption}</p>
          )}
        </div>
        {footer}
      </div>
    );
  }

  // -- Animated Intro --
  if (layout === 'animated-intro') {
    const animationType = (slide as ParsedSlide & { animationType?: string }).animationType || 'fade-in';
    const animLabel = animationType.replace('-', ' ').replace(/\b\w/g, (l: string) => l.toUpperCase());
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', backgroundColor: t.bg }}>
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '28px 40px' }}>
          <div style={{
            position: 'absolute', top: '12px', right: '14px',
            padding: '3px 10px', borderRadius: '12px',
            backgroundColor: `${t.accent}12`, border: `1px solid ${t.accent}25`,
          }}>
            <span style={{
              fontFamily: "'Rajdhani', sans-serif", fontSize: '8px', fontWeight: 700,
              color: t.accent, letterSpacing: '0.5px',
            }}>{animLabel}</span>
          </div>
          <h2 style={{
            fontFamily: "'Rajdhani', sans-serif", fontWeight: 700,
            fontSize: 'clamp(20px, 2.6vw, 28px)', color: t.titleColor,
            letterSpacing: '2px', textTransform: 'uppercase', textAlign: 'center',
            margin: '0 0 14px',
            animation: animationType === 'fade-in' ? 'previewFadeIn 1s ease both' :
              animationType === 'slide-up' ? 'previewSlideUp 0.8s ease both' :
              animationType === 'zoom-in' ? 'previewZoomIn 0.8s ease both' : 'none',
          }}>{slide.title}</h2>
          {slide.bullets[0]?.trim() && (
            <p style={{
              fontFamily: "'Quicksand', sans-serif", fontSize: 'clamp(12px, 1.4vw, 14px)',
              color: t.bodyColor, textAlign: 'center', lineHeight: 1.7, maxWidth: '80%',
              opacity: 0.85,
              animation: animationType === 'stagger' ? 'previewFadeIn 1.2s ease 0.3s both' : 'none',
            }}>{slide.bullets[0]}</p>
          )}
          <div style={{ display: 'flex', gap: '5px', marginTop: '14px' }}>
            {[0, 1, 2].map(i => (
              <div key={i} style={{
                width: '7px', height: '7px', borderRadius: '50%',
                backgroundColor: t.accent, opacity: 0.1 + (i * 0.35),
              }} />
            ))}
          </div>
        </div>
        {footer}
      </div>
    );
  }

  // -- Comparison --
  if (layout === 'comparison') {
    const mid = Math.ceil(slide.bullets.length / 2);
    return (
      <div style={{ display: 'flex', flexDirection: 'column', height: '100%', backgroundColor: t.bg }}>
        <div style={{ padding: '18px 20px 6px' }}>
          <h2 style={{
            fontFamily: "'Rajdhani', sans-serif", fontWeight: 700,
            fontSize: 'clamp(16px, 2vw, 20px)', color: t.titleColor,
            letterSpacing: '1.5px', textTransform: 'uppercase', margin: 0, textAlign: 'center',
          }}>{slide.title}</h2>
        </div>
        <div style={{ flex: 1, display: 'flex', gap: '3px', padding: '10px 20px' }}>
          <div style={{
            flex: 1, backgroundColor: `${t.accent}06`, borderRadius: '8px 0 0 8px',
            padding: '14px', display: 'flex', flexDirection: 'column',
          }}>
            <div style={{
              fontFamily: "'Rajdhani', sans-serif", fontSize: '10px', fontWeight: 700,
              color: t.accent, letterSpacing: '1px', textTransform: 'uppercase', marginBottom: '10px',
            }}>OPTION A</div>
            {renderBullets(slide.bullets.slice(0, mid), t)}
          </div>
          <div style={{ width: '2px', backgroundColor: `${t.accent}25`, flexShrink: 0 }} />
          <div style={{
            flex: 1, backgroundColor: `${t.accentSecondary}06`, borderRadius: '0 8px 8px 0',
            padding: '14px', display: 'flex', flexDirection: 'column',
          }}>
            <div style={{
              fontFamily: "'Rajdhani', sans-serif", fontSize: '10px', fontWeight: 700,
              color: t.accentSecondary, letterSpacing: '1px', textTransform: 'uppercase', marginBottom: '10px',
            }}>OPTION B</div>
            {renderBullets(slide.bullets.slice(mid), t)}
          </div>
        </div>
        {footer}
      </div>
    );
  }

  // -- Default: Title + Bullets --
  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', backgroundColor: t.bg }}>
      <div style={{ position: 'absolute', left: 0, top: 0, bottom: 0, width: '4px', backgroundColor: t.accent }} />
      <div style={{ flex: 1, padding: '28px 48px 28px 32px', display: 'flex', flexDirection: 'column', justifyContent: 'flex-start', overflow: 'hidden' }}>
        <h2 style={{
          fontFamily: "'Rajdhani', sans-serif", fontWeight: 700,
          fontSize: 'clamp(16px, 2.2vw, 22px)', color: t.titleColor,
          letterSpacing: '1.5px', textTransform: 'uppercase', margin: '0 0 8px', paddingLeft: '12px',
        }}>{slide.title}</h2>
        <div style={{ height: '1px', backgroundColor: `${t.accent}30`, margin: '0 0 16px 12px' }} />
        <div style={{ flex: 1, overflow: 'auto', paddingLeft: '12px' }}>
          {renderBullets(slide.bullets, t)}
        </div>
      </div>
      {footer}
    </div>
  );
}

function renderBullets(bullets: string[], t: ThemeColors) {
  return bullets.map((bullet, i) => (
    bullet.trim() ? (
      <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: '10px', marginBottom: '10px' }}>
        <span style={{ width: '6px', height: '6px', borderRadius: '50%', backgroundColor: t.accent, flexShrink: 0, marginTop: '7px' }} />
        <span style={{ fontFamily: "'Quicksand', sans-serif", fontSize: 'clamp(11px, 1.4vw, 14px)', color: t.bodyColor, lineHeight: 1.6 }}>{bullet}</span>
      </div>
    ) : null
  ));
}

/* ------------------------------------------------------------------ */
/*  Main Component                                                     */
/* ------------------------------------------------------------------ */

export function SlidePreview({ title, content, colors, isDark }: SlidePreviewProps) {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [viewMode, setViewMode] = useState<'single' | 'grid'>('single');
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [presenting, setPresenting] = useState(false);
  const [showNotes, setShowNotes] = useState(false);
  const [showPresenterNotes, setShowPresenterNotes] = useState(false);

  const { isMobile } = useResponsive();
  const thumbnailStripRef = useRef<HTMLDivElement>(null);
  const touchStartX = useRef<number | null>(null);

  const slides = useMemo(() => parseMarkdownToSlides(content), [content]);
  const totalSlides = slides.length;
  const t = DEFAULT_THEME;

  const goTo = useCallback((idx: number) => {
    if (idx >= 0 && idx < totalSlides) setCurrentSlide(idx);
  }, [totalSlides]);

  const handleDownload = async () => {
    setDownloading(true);
    try { await downloadSlidesAsPptx(title, content); }
    catch (err) { console.error('PPTX download failed:', err); }
    finally { setDownloading(false); }
  };

  // Auto-scroll thumbnail strip to active
  useEffect(() => {
    if (thumbnailStripRef.current) {
      const thumb = thumbnailStripRef.current.children[currentSlide] as HTMLElement;
      if (thumb) thumb.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'center' });
    }
  }, [currentSlide]);

  /* ----- Presentation Mode ----- */
  const startPresentation = useCallback(() => {
    setPresenting(true);
    setShowPresenterNotes(false);
    try { document.documentElement.requestFullscreen?.(); } catch { /* noop */ }
  }, []);

  const stopPresentation = useCallback(() => {
    setPresenting(false);
    try { if (document.fullscreenElement) document.exitFullscreen?.(); } catch { /* noop */ }
  }, []);

  // Keyboard navigation for presentation
  useEffect(() => {
    if (!presenting) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') { stopPresentation(); return; }
      if (e.key === 'ArrowRight' || e.key === ' ') { e.preventDefault(); goTo(Math.min(currentSlide + 1, totalSlides - 1)); }
      if (e.key === 'ArrowLeft') { e.preventDefault(); goTo(Math.max(currentSlide - 1, 0)); }
      if (e.key === 'n' || e.key === 'N') { setShowPresenterNotes(p => !p); }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [presenting, currentSlide, totalSlides, goTo, stopPresentation]);

  // Exit presentation on fullscreen exit
  useEffect(() => {
    const handler = () => { if (!document.fullscreenElement && presenting) setPresenting(false); };
    document.addEventListener('fullscreenchange', handler);
    return () => document.removeEventListener('fullscreenchange', handler);
  }, [presenting]);

  // Touch swipe for presentation mode & mobile
  const handleTouchStart = useCallback((e: React.TouchEvent) => {
    touchStartX.current = e.touches[0].clientX;
  }, []);

  const handleTouchEnd = useCallback((e: React.TouchEvent) => {
    if (touchStartX.current === null) return;
    const dx = e.changedTouches[0].clientX - touchStartX.current;
    if (Math.abs(dx) > 50) {
      if (dx < 0) goTo(Math.min(currentSlide + 1, totalSlides - 1));
      else goTo(Math.max(currentSlide - 1, 0));
    }
    touchStartX.current = null;
  }, [currentSlide, totalSlides, goTo]);

  /* ----- Empty State ----- */
  if (totalSlides === 0) {
    return (
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        height: '100%', color: colors.textMuted, fontSize: '14px',
        fontFamily: "'Quicksand', sans-serif",
      }}>
        No slide content to preview
      </div>
    );
  }

  /* ----- Presentation Mode Render ----- */
  if (presenting) {
    const currentNotes = slides[currentSlide]?.notes || '';
    return (
      <div
        style={{
          position: 'fixed', inset: 0, zIndex: 99999, backgroundColor: '#000',
          display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
          cursor: 'none',
        }}
        onTouchStart={handleTouchStart}
        onTouchEnd={handleTouchEnd}
        onClick={(e) => {
          const rect = (e.target as HTMLElement).getBoundingClientRect();
          const x = e.clientX - rect.left;
          if (x > rect.width / 2) goTo(Math.min(currentSlide + 1, totalSlides - 1));
          else goTo(Math.max(currentSlide - 1, 0));
        }}
      >
        {/* Slide */}
        <div style={{
          width: '100vw', height: '100vh', display: 'flex',
          alignItems: 'center', justifyContent: 'center', position: 'relative',
        }}>
          <div style={{
            width: '100%', height: '100%', maxWidth: 'calc(100vh * 16 / 9)',
            aspectRatio: '16/9', position: 'relative', overflow: 'hidden',
            transition: 'opacity 0.3s ease',
          }}>
            <SlideRenderer slide={slides[currentSlide]} slideIndex={currentSlide} totalSlides={totalSlides} title={title} t={t} />
          </div>
        </div>

        {/* Bottom bar */}
        <div style={{
          position: 'fixed', bottom: 0, left: 0, right: 0, height: '40px',
          display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '12px',
          backgroundColor: 'rgba(0,0,0,0.7)', opacity: 0.8,
          transition: 'opacity 0.3s ease',
        }}>
          <span style={{ fontFamily: "'Rajdhani', sans-serif", fontSize: '13px', fontWeight: 600, color: '#FEC00F', letterSpacing: '1px' }}>
            {currentSlide + 1} / {totalSlides}
          </span>
          <button onClick={(e) => { e.stopPropagation(); stopPresentation(); }}
            style={{ background: 'none', border: '1px solid #555', borderRadius: '4px', color: '#999', cursor: 'pointer', padding: '4px 10px', fontSize: '10px', fontFamily: "'Rajdhani', sans-serif", fontWeight: 600, letterSpacing: '0.5px' }}>
            ESC TO EXIT
          </button>
          <button onClick={(e) => { e.stopPropagation(); setShowPresenterNotes(p => !p); }}
            title="Toggle notes (N)"
            style={{
              background: showPresenterNotes ? 'rgba(254,192,15,0.15)' : 'none',
              border: showPresenterNotes ? '1px solid rgba(254,192,15,0.4)' : '1px solid #555',
              borderRadius: '4px', color: showPresenterNotes ? '#FEC00F' : '#999',
              cursor: 'pointer', padding: '4px 8px', display: 'flex', alignItems: 'center',
            }}>
            <StickyNote size={12} />
          </button>
        </div>

        {/* Speaker notes overlay */}
        {showPresenterNotes && currentNotes && (
          <div style={{
            position: 'fixed', bottom: '48px', left: '50%', transform: 'translateX(-50%)',
            maxWidth: '600px', width: '90%', padding: '16px 20px',
            backgroundColor: 'rgba(0,0,0,0.85)', borderRadius: '10px',
            border: '1px solid rgba(254,192,15,0.2)',
          }}
            onClick={(e) => e.stopPropagation()}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '8px' }}>
              <StickyNote size={12} color="#FEC00F" />
              <span style={{ fontFamily: "'Rajdhani', sans-serif", fontSize: '10px', fontWeight: 700, color: '#FEC00F', letterSpacing: '1px' }}>SPEAKER NOTES</span>
            </div>
            <p style={{ fontFamily: "'Quicksand', sans-serif", fontSize: '13px', color: '#ccc', lineHeight: 1.7, margin: 0, whiteSpace: 'pre-wrap' }}>
              {currentNotes}
            </p>
          </div>
        )}
      </div>
    );
  }

  /* ----- Standard View ----- */
  const currentNotes = slides[currentSlide]?.notes || '';

  const containerStyle: React.CSSProperties = isFullscreen
    ? { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, zIndex: 9999, backgroundColor: isDark ? '#0a0a0a' : '#f5f5f5', display: 'flex', flexDirection: 'column' }
    : { display: 'flex', flexDirection: 'column', height: '100%' };

  return (
    <div style={containerStyle}>
      {/* ========== Toolbar ========== */}
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: isMobile ? '8px 12px' : '10px 20px',
        borderBottom: `1px solid ${colors.border}`,
        backgroundColor: isDark ? '#111' : '#fafafa', flexShrink: 0,
        gap: '8px',
      }}>
        {/* Left: slide counter */}
        <span style={{
          fontFamily: "'Rajdhani', sans-serif", fontWeight: 700,
          fontSize: '13px', color: colors.primaryYellow,
          letterSpacing: '1px', textTransform: 'uppercase', whiteSpace: 'nowrap',
        }}>
          SLIDE {currentSlide + 1} / {totalSlides}
        </span>

        {/* Center: navigation arrows (single mode only) */}
        {viewMode === 'single' && !isMobile && (
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
            <NavButton onClick={() => goTo(currentSlide - 1)} disabled={currentSlide === 0} colors={colors} isDark={isDark}>
              <ChevronLeft size={16} />
            </NavButton>
            <NavButton onClick={() => goTo(currentSlide + 1)} disabled={currentSlide === totalSlides - 1} colors={colors} isDark={isDark}>
              <ChevronRight size={16} />
            </NavButton>
          </div>
        )}

        {/* Right: actions */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
          {/* Notes toggle */}
          <ToolbarButton
            onClick={() => setShowNotes(!showNotes)}
            active={showNotes}
            colors={colors} isDark={isDark} title="Speaker Notes"
          >
            <StickyNote size={14} />
          </ToolbarButton>

          {!isMobile && (
            <ToolbarButton
              onClick={() => setViewMode(viewMode === 'single' ? 'grid' : 'single')}
              active={viewMode === 'grid'}
              colors={colors} isDark={isDark}
              title={viewMode === 'single' ? 'Grid view' : 'Single view'}
            >
              {viewMode === 'single' ? <Grid size={14} /> : <Layers size={14} />}
            </ToolbarButton>
          )}

          <ToolbarButton
            onClick={() => setIsFullscreen(!isFullscreen)}
            colors={colors} isDark={isDark}
            title={isFullscreen ? 'Exit fullscreen' : 'Fullscreen'}
          >
            {isFullscreen ? <Minimize2 size={14} /> : <Maximize2 size={14} />}
          </ToolbarButton>

          {/* Present button */}
          <button onClick={startPresentation} style={{
            display: 'flex', alignItems: 'center', gap: '6px',
            padding: '7px 14px',
            backgroundColor: isDark ? '#00DED1' : '#00b8ab',
            color: '#1a1a1a', border: 'none', borderRadius: '8px', cursor: 'pointer',
            fontFamily: "'Rajdhani', sans-serif", fontWeight: 700,
            fontSize: '12px', letterSpacing: '0.5px',
          }}>
            <Play size={13} />
            {!isMobile && 'PRESENT'}
          </button>

          <button onClick={handleDownload} disabled={downloading} style={{
            display: 'flex', alignItems: 'center', gap: '6px',
            padding: '7px 14px',
            background: `linear-gradient(135deg, ${colors.primaryYellow}, #FFD700)`,
            color: '#1a1a1a', border: 'none', borderRadius: '8px',
            cursor: downloading ? 'wait' : 'pointer',
            fontFamily: "'Rajdhani', sans-serif", fontWeight: 700,
            fontSize: '12px', letterSpacing: '0.5px',
            opacity: downloading ? 0.7 : 1,
          }}>
            <Download size={13} />
            {!isMobile && (downloading ? 'EXPORTING...' : '.PPTX')}
          </button>
        </div>
      </div>

      {/* ========== Slide Area ========== */}
      <div style={{ flex: 1, overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
        <div
          style={{
            flex: 1, overflow: 'auto',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            padding: viewMode === 'grid' ? '20px' : (isMobile ? '12px' : '24px'),
            backgroundColor: isDark ? '#0a0a0a' : '#e8e8e8',
          }}
          onTouchStart={viewMode === 'single' ? handleTouchStart : undefined}
          onTouchEnd={viewMode === 'single' ? handleTouchEnd : undefined}
        >
          {viewMode === 'single' ? (
            <div style={{
              width: '100%',
              maxWidth: isFullscreen ? '1100px' : '820px',
              aspectRatio: '16 / 9',
              borderRadius: '8px',
              boxShadow: '0 8px 32px rgba(0,0,0,0.4)',
              overflow: 'hidden',
              position: 'relative',
            }}>
              <SlideRenderer
                slide={slides[currentSlide]}
                slideIndex={currentSlide}
                totalSlides={totalSlides}
                title={title}
                t={t}
              />
            </div>
          ) : (
            <GridView
              slides={slides}
              currentSlide={currentSlide}
              title={title}
              colors={colors}
              isDark={isDark}
              t={t}
              onSelect={(i) => { setCurrentSlide(i); setViewMode('single'); }}
            />
          )}
        </div>

        {/* ========== Thumbnail Navigator Strip (single mode) ========== */}
        {viewMode === 'single' && (
          <div style={{
            flexShrink: 0, borderTop: `1px solid ${colors.border}`,
            backgroundColor: isDark ? '#111' : '#f5f5f5',
            padding: '8px 12px',
          }}>
            <div
              ref={thumbnailStripRef}
              style={{
                display: 'flex', gap: '8px', overflowX: 'auto',
                WebkitOverflowScrolling: 'touch', scrollbarWidth: 'none',
                paddingBottom: '4px',
              }}
            >
              {slides.map((slide, i) => {
                const isActive = i === currentSlide;
                return (
                  <button
                    key={i}
                    onClick={() => goTo(i)}
                    style={{
                      flexShrink: 0,
                      width: isMobile ? '72px' : '88px',
                      aspectRatio: '16/9',
                      borderRadius: '4px',
                      border: isActive ? `2px solid ${colors.primaryYellow}` : `1px solid ${isDark ? '#333' : '#ccc'}`,
                      overflow: 'hidden',
                      cursor: 'pointer',
                      position: 'relative',
                      backgroundColor: t.bg,
                      boxShadow: isActive ? `0 0 8px ${colors.primaryYellow}30` : 'none',
                      transition: 'all 0.15s ease',
                      padding: 0,
                    }}
                  >
                    {/* Mini render */}
                    <div style={{ transform: 'scale(0.12)', transformOrigin: 'top left', width: `${100/0.12}%`, height: `${100/0.12}%`, pointerEvents: 'none' }}>
                      <SlideRenderer slide={slide} slideIndex={i} totalSlides={totalSlides} title={title} t={t} />
                    </div>
                    {/* Slide number badge */}
                    <div style={{
                      position: 'absolute', bottom: '2px', right: '4px',
                      fontFamily: "'Rajdhani', sans-serif", fontSize: '8px', fontWeight: 700,
                      color: isActive ? colors.primaryYellow : (isDark ? '#555' : '#999'),
                    }}>{i + 1}</div>
                  </button>
                );
              })}
            </div>
          </div>
        )}

        {/* ========== Notes Tray ========== */}
        {showNotes && viewMode === 'single' && (
          <div style={{
            flexShrink: 0, borderTop: `1px solid ${colors.border}`,
            backgroundColor: isDark ? '#111' : '#fafafa',
            padding: '12px 20px', maxHeight: '150px', overflowY: 'auto',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '6px' }}>
              <StickyNote size={12} color={colors.primaryYellow} />
              <span style={{
                fontFamily: "'Rajdhani', sans-serif", fontSize: '10px', fontWeight: 700,
                color: colors.primaryYellow, letterSpacing: '1px',
              }}>SPEAKER NOTES</span>
            </div>
            {currentNotes ? (
              <p style={{
                fontFamily: "'Quicksand', sans-serif", fontSize: '12px',
                color: colors.text, lineHeight: 1.7, margin: 0, whiteSpace: 'pre-wrap',
              }}>{currentNotes}</p>
            ) : (
              <p style={{
                fontFamily: "'Quicksand', sans-serif", fontSize: '12px',
                color: colors.textMuted, lineHeight: 1.7, margin: 0, fontStyle: 'italic',
              }}>No notes for this slide.</p>
            )}
          </div>
        )}

        {/* Mobile nav arrows */}
        {isMobile && viewMode === 'single' && (
          <div style={{
            flexShrink: 0, display: 'flex', borderTop: `1px solid ${colors.border}`,
            backgroundColor: isDark ? '#111' : '#fafafa',
          }}>
            <button onClick={() => goTo(currentSlide - 1)} disabled={currentSlide === 0}
              style={{
                flex: 1, padding: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center',
                background: 'none', border: 'none', cursor: currentSlide === 0 ? 'not-allowed' : 'pointer',
                color: currentSlide === 0 ? colors.borderSubtle : colors.textMuted, minHeight: '48px',
              }}>
              <ChevronLeft size={20} />
            </button>
            <div style={{ display: 'flex', alignItems: 'center', padding: '0 16px' }}>
              <span style={{ fontFamily: "'Rajdhani', sans-serif", fontWeight: 700, fontSize: '13px', color: colors.textMuted }}>
                {currentSlide + 1} / {totalSlides}
              </span>
            </div>
            <button onClick={() => goTo(currentSlide + 1)} disabled={currentSlide === totalSlides - 1}
              style={{
                flex: 1, padding: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center',
                background: 'none', border: 'none', cursor: currentSlide === totalSlides - 1 ? 'not-allowed' : 'pointer',
                color: currentSlide === totalSlides - 1 ? colors.borderSubtle : colors.textMuted, minHeight: '48px',
              }}>
              <ChevronRight size={20} />
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

/* ================================================================== */
/*  Grid View                                                          */
/* ================================================================== */

function GridView({ slides, currentSlide, title, colors, isDark, t, onSelect }: {
  slides: ParsedSlide[]; currentSlide: number; title: string;
  colors: Record<string, string>; isDark: boolean; t: ThemeColors;
  onSelect: (i: number) => void;
}) {
  return (
    <div style={{
      display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))',
      gap: '16px', width: '100%', maxWidth: '1200px',
    }}>
      {slides.map((slide, i) => {
        const isActive = i === currentSlide;
        return (
          <button key={i} onClick={() => onSelect(i)}
            style={{
              aspectRatio: '16 / 9', borderRadius: '6px',
              border: isActive ? `2px solid ${t.accent}` : '2px solid transparent',
              overflow: 'hidden', cursor: 'pointer', position: 'relative',
              textAlign: 'left', transition: 'all 0.15s ease', padding: 0,
              boxShadow: isActive ? `0 4px 16px ${t.accent}30` : '0 2px 8px rgba(0,0,0,0.3)',
            }}>
            <SlideRenderer slide={slide} slideIndex={i} totalSlides={slides.length} title={title} t={t} />
            <div style={{
              position: 'absolute', bottom: '22px', right: '8px',
              fontFamily: "'Rajdhani', sans-serif", fontSize: '10px', fontWeight: 700,
              color: isActive ? t.accent : t.mutedColor,
            }}>{i + 1}</div>
          </button>
        );
      })}
    </div>
  );
}

/* ================================================================== */
/*  Shared small components                                            */
/* ================================================================== */

function NavButton({ onClick, disabled, children, colors, isDark }: {
  onClick: () => void; disabled: boolean;
  children: React.ReactNode; colors: Record<string, string>; isDark: boolean;
}) {
  return (
    <button onClick={onClick} disabled={disabled}
      style={{
        width: '32px', height: '32px',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        border: `1px solid ${colors.border}`, borderRadius: '8px',
        backgroundColor: 'transparent',
        color: disabled ? (isDark ? '#333' : '#ccc') : colors.text,
        cursor: disabled ? 'not-allowed' : 'pointer',
        transition: 'all 0.15s ease',
      }}>
      {children}
    </button>
  );
}

function ToolbarButton({ onClick, active, children, colors, isDark, title }: {
  onClick: () => void; active?: boolean;
  children: React.ReactNode; colors: Record<string, string>;
  isDark: boolean; title?: string;
}) {
  return (
    <button onClick={onClick} title={title}
      style={{
        width: '32px', height: '32px',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        border: `1px solid ${active ? colors.primaryYellow : colors.border}`,
        borderRadius: '8px',
        backgroundColor: active ? `${colors.primaryYellow}15` : 'transparent',
        color: active ? colors.primaryYellow : colors.textMuted,
        cursor: 'pointer', transition: 'all 0.15s ease',
      }}>
      {children}
    </button>
  );
}

/* Inject animation keyframes */
if (typeof document !== 'undefined') {
  const KEYFRAMES_ID = 'slide-preview-anims';
  if (!document.getElementById(KEYFRAMES_ID)) {
    const style = document.createElement('style');
    style.id = KEYFRAMES_ID;
    style.textContent = `
      @keyframes previewFadeIn { from { opacity: 0; } to { opacity: 1; } }
      @keyframes previewSlideUp { from { opacity: 0; transform: translateY(30px); } to { opacity: 1; transform: translateY(0); } }
      @keyframes previewZoomIn { from { opacity: 0; transform: scale(0.85); } to { opacity: 1; transform: scale(1); } }
    `;
    document.head.appendChild(style);
  }
}

export default SlidePreview;
