
"""
AFL Templates - Complete templates for standalone and composite strategies.
"""

AFL_TEMPLATE_STANDALONE = '''
// ============================================================
// STANDALONE STRATEGY TEMPLATE
// Generated by Analyst by Potomac
// ============================================================

_SECTION_BEGIN("Strategy Parameters");
// --------------------------------------------------------
// Parameter Structure: Default, Min, Max, Step
// Always use Param() + Optimize() pattern
// --------------------------------------------------------

// RSI Parameters
rsiDefault = 14; rsiMin = 2; rsiMax = 50; rsiStep = 1;
rsiLength_Dflt = Param("RSI Period", rsiDefault, rsiMin, rsiMax, rsiStep);
rsiLength = Optimize("RSI Period", rsiLength_Dflt, rsiMin, rsiMax, rsiStep);

rsiOBDefault = 70; rsiOBMin = 60; rsiOBMax = 90; rsiOBStep = 5;
rsiOverbought_Dflt = Param("RSI Overbought", rsiOBDefault, rsiOBMin, rsiOBMax, rsiOBStep);
rsiOverbought = Optimize("RSI Overbought", rsiOverbought_Dflt, rsiOBMin, rsiOBMax, rsiOBStep);

rsiOSDefault = 30; rsiOSMin = 10; rsiOSMax = 40; rsiOSStep = 5;
rsiOversold_Dflt = Param("RSI Oversold", rsiOSDefault, rsiOSMin, rsiOSMax, rsiOSStep);
rsiOversold = Optimize("RSI Oversold", rsiOversold_Dflt, rsiOSMin, rsiOSMax, rsiOSStep);

// Moving Average Parameters
maDefault = 200; maMin = 10; maMax = 500; maStep = 5;
maLength_Dflt = Param("MA Period", maDefault, maMin, maMax, maStep);
maLength = Optimize("MA Period", maLength_Dflt, maMin, maMax, maStep);

_SECTION_END();

_SECTION_BEGIN("Backtest Settings");
// --------------------------------------------------------
// Execution and Position Settings
// --------------------------------------------------------
SetOption("MaxOpenPositions", 1);
SetTradeDelays(0, 0, 0, 0);  // Execute on Close; use (1,1,1,1) for Open
SetOption("UsePrevBarEquityForPosSizing", True);
SetOption("AllowPositionShrinking", True);
SetOption("CommissionMode", 2);
SetOption("CommissionAmount", 0.0005);  // 0.05% per trade
SetOption("InitialEquity", 100000);
SetOption("AccountMargin", 1);
PositionSize = 100;  // 100% of equity per trade
_SECTION_END();

_SECTION_BEGIN("Indicators");
// --------------------------------------------------------
// Calculate All Indicators
// IMPORTANT: Use proper naming - never shadow built-in functions
// --------------------------------------------------------

// RSI Indicator (single argument - no array parameter)
RSI_Val = RSI(rsiLength);

// Moving Average (double argument - array, period)
MA_Val = MA(Close, maLength);

// ATR for volatility (single argument)
ATR_Val = ATR(14);

_SECTION_END();

_SECTION_BEGIN("Trading Logic");
// --------------------------------------------------------
// Entry and Exit Conditions
// --------------------------------------------------------

// Initialize signals
Buy = Sell = Short = Cover = 0;

// Long Entry: RSI oversold AND price above MA (trend filter)
BuyCondition = RSI_Val < rsiOversold AND Close > MA_Val;

// Long Exit: RSI overbought OR price below MA
SellCondition = RSI_Val > rsiOverbought OR Close < MA_Val;

// Assign signals
Buy = BuyCondition;
Sell = SellCondition;

// Remove consecutive signals (CRITICAL for proper backtesting)
Buy = ExRem(Buy, Sell);
Sell = ExRem(Sell, Buy);

// Set trade prices
BuyPrice = Close;
SellPrice = Close;

_SECTION_END();

_SECTION_BEGIN("Chart Visualization");
// --------------------------------------------------------
// Price Chart and Signal Markers
// --------------------------------------------------------

// Plot price
Plot(Close, "Price", colorDefault, styleCandle);

// Plot moving average
Plot(MA_Val, "MA(" + NumToStr(maLength, 1.0) + ")", colorBlue, styleLine | styleThick);

// Plot buy/sell arrows
PlotShapes(IIf(Buy, shapeUpArrow, shapeNone), colorGreen, 0, Low, -15);
PlotShapes(IIf(Sell, shapeDownArrow, shapeNone), colorRed, 0, High, -15);

// Background color for trend
SetBarFillColor(IIf(Close > MA_Val, colorPaleGreen, colorLightOrange));

_SECTION_END();

_SECTION_BEGIN("RSI Panel");
// --------------------------------------------------------
// RSI Indicator Panel
// --------------------------------------------------------

Plot(RSI_Val, "RSI(" + NumToStr(rsiLength, 1.0) + ")", colorPurple, styleLine | styleOwnScale, 0, 100);
Plot(rsiOverbought, "Overbought", colorRed, styleDashed | styleOwnScale, 0, 100);
Plot(rsiOversold, "Oversold", colorGreen, styleDashed | styleOwnScale, 0, 100);
Plot(50, "Midline", colorGrey40, styleDashed | styleOwnScale, 0, 100);

_SECTION_END();

_SECTION_BEGIN("Exploration");
// --------------------------------------------------------
// Analysis/Exploration Output
// --------------------------------------------------------

Filter = Buy OR Sell;

// Signal column with text
SignalType = IIf(Buy, 1, IIf(Sell, 2, 0));
AddMultiTextColumn(SignalType, "None\\nBUY\\nSELL", "Signal", 1, 
    IIf(Buy, colorWhite, IIf(Sell, colorWhite, colorDefault)),
    IIf(Buy, colorGreen, IIf(Sell, colorRed, colorDefault)), 80);

AddColumn(Close, "Close", 1.2);
AddColumn(RSI_Val, "RSI", 1.1);
AddColumn(MA_Val, "MA", 1.2);
AddColumn(Volume, "Volume", 1.0);

_SECTION_END();
'''

AFL_TEMPLATE_COMPOSITE = '''
// ============================================================
// COMPOSITE STRATEGY MODULE: [PREFIX]
// For use with Master Template - DO NOT RUN STANDALONE
// ============================================================
// 
// INSTRUCTIONS:
// 1. Replace [PREFIX] with unique strategy identifier (e.g., RSIMomentum)
// 2. This file should be saved in AmiBroker\\Formulas\\Custom\\
// 3. Include in Master template: #include "ThisFile.afl"
// 4. Map signals in Master: [PREFIX]_Buy_Signal = IIf(use[PREFIX], Buy[PREFIX], 0);
//
// RULES:
// - NO Plot() statements
// - NO AddColumn() or Filter
// - NO SetOption() or backtest settings
// - NO Buy/Sell direct assignment (only Buy[PREFIX]/Sell[PREFIX])
// ============================================================

// --- Strategy Parameters ---
// Note: Master template controls optimization toggle
// Use Param() for slider adjustment

[PREFIX]_rsiLength = Param("[PREFIX] RSI Period", 14, 2, 50, 1);
[PREFIX]_rsiOB = Param("[PREFIX] RSI Overbought", 70, 60, 90, 5);
[PREFIX]_rsiOS = Param("[PREFIX] RSI Oversold", 30, 10, 40, 5);
[PREFIX]_maLength = Param("[PREFIX] MA Period", 200, 10, 500, 10);

// --- Indicator Calculations ---
// Prefix all variables to avoid conflicts with other modules

[PREFIX]_RSI_Val = RSI([PREFIX]_rsiLength);
[PREFIX]_MA_Val = MA(Close, [PREFIX]_maLength);
[PREFIX]_TrendUp = Close > [PREFIX]_MA_Val;

// --- Signal Generation ---
// MUST use unique signal names: Buy[PREFIX], Sell[PREFIX]

Buy[PREFIX] = [PREFIX]_RSI_Val < [PREFIX]_rsiOS AND [PREFIX]_TrendUp;
Sell[PREFIX] = [PREFIX]_RSI_Val > [PREFIX]_rsiOB OR NOT [PREFIX]_TrendUp;

// --- END OF MODULE ---
// Master template will handle:
// - Signal toggling (enable/disable this strategy)
// - Signal mapping to voting engine
// - ExRem() cleanup
// - Charting and exploration
// - Position sizing and risk management
'''

AFL_TEMPLATE_MASTER = '''
// ============================================================
// MASTER TEMPLATE - COMPOSITE SYSTEM CONTROLLER
// Generated by Analyst by Potomac
// ============================================================

_SECTION_BEGIN("Master Configuration");

// Strategy Toggles
useStrategy1 = ParamToggle("Enable Strategy1", "No|Yes", 1);
useStrategy2 = ParamToggle("Enable Strategy2", "No|Yes", 1);
useStrategy3 = ParamToggle("Enable Strategy3", "No|Yes", 0);

// Voting Method
votingMethod = ParamList("Voting Method", "Majority|Any|All|Weighted", 0);

// Optimization Control
enableOptimization = ParamToggle("Enable Optimization", "No|Yes", 0);

_SECTION_END();

_SECTION_BEGIN("Import Strategies");
// --------------------------------------------------------
// Import individual strategy modules
// Each module defines: BuyStrategyName, SellStrategyName
// --------------------------------------------------------

// #include "Strategy1.afl"
// #include "Strategy2.afl"
// #include "Strategy3.afl"

_SECTION_END();

_SECTION_BEGIN("Signal Mapping");
// --------------------------------------------------------
// Map strategy signals to voting engine
// Apply toggles to enable/disable each strategy
// --------------------------------------------------------

Strategy1_Buy = IIf(useStrategy1, BuyStrategy1, 0);
Strategy1_Sell = IIf(useStrategy1, SellStrategy1, 0);

Strategy2_Buy = IIf(useStrategy2, BuyStrategy2, 0);
Strategy2_Sell = IIf(useStrategy2, SellStrategy2, 0);

Strategy3_Buy = IIf(useStrategy3, BuyStrategy3, 0);
Strategy3_Sell = IIf(useStrategy3, SellStrategy3, 0);

_SECTION_END();

_SECTION_BEGIN("Voting Engine");
// --------------------------------------------------------
// Combine signals based on voting method
// --------------------------------------------------------

BuyVotes = Strategy1_Buy + Strategy2_Buy + Strategy3_Buy;
SellVotes = Strategy1_Sell + Strategy2_Sell + Strategy3_Sell;
ActiveStrategies = useStrategy1 + useStrategy2 + useStrategy3;

// Voting logic
if (votingMethod == "Majority") {
    CompositeBuy = BuyVotes > ActiveStrategies / 2;
    CompositeSell = SellVotes > ActiveStrategies / 2;
} else if (votingMethod == "Any") {
    CompositeBuy = BuyVotes >= 1;
    CompositeSell = SellVotes >= 1;
} else if (votingMethod == "All") {
    CompositeBuy = BuyVotes == ActiveStrategies;
    CompositeSell = SellVotes == ActiveStrategies;
} else {
    // Weighted - implement custom weighting
    CompositeBuy = BuyVotes >= 2;
    CompositeSell = SellVotes >= 2;
}

_SECTION_END();

_SECTION_BEGIN("Final Signals");
// --------------------------------------------------------
// Assign final Buy/Sell from composite
// --------------------------------------------------------

Buy = CompositeBuy;
Sell = CompositeSell;
Short = Cover = 0;

// Clean signals
Buy = ExRem(Buy, Sell);
Sell = ExRem(Sell, Buy);

_SECTION_END();

_SECTION_BEGIN("Backtest Settings");
SetOption("MaxOpenPositions", 1);
SetTradeDelays(0, 0, 0, 0);
SetOption("InitialEquity", 100000);
PositionSize = 100;
_SECTION_END();

_SECTION_BEGIN("Chart");
Plot(Close, "Price", colorDefault, styleCandle);
PlotShapes(IIf(Buy, shapeUpArrow, shapeNone), colorGreen, 0, Low, -15);
PlotShapes(IIf(Sell, shapeDownArrow, shapeNone), colorRed, 0, High, -15);
_SECTION_END();

_SECTION_BEGIN("Exploration");
Filter = Buy OR Sell;
AddColumn(Close, "Close", 1.2);
AddColumn(BuyVotes, "Buy Votes", 1.0);
AddColumn(SellVotes, "Sell Votes", 1.0);
AddColumn(Buy, "Final Buy", 1.0);
AddColumn(Sell, "Final Sell", 1.0);
_SECTION_END();
'''


def get_template(strategy_type: str) -> str:
    """
    Get appropriate template based on strategy type.

    Args:
        strategy_type: 'standalone', 'composite', or 'master'

    Returns:
        AFL template string
    """
    strategy_type_lower = strategy_type.lower().strip()

    if strategy_type_lower == "composite" or strategy_type_lower == "module":
        return AFL_TEMPLATE_COMPOSITE
    elif strategy_type_lower == "master":
        return AFL_TEMPLATE_MASTER
    else:
        return AFL_TEMPLATE_STANDALONE


def get_minimal_template() -> str:
    """Get a minimal AFL template for quick starts."""
    return '''
_SECTION_BEGIN("Quick Strategy");

// Parameters
period = Param("Period", 14, 2, 50, 1);

// Indicator
RSI_Val = RSI(period);

// Signals
Buy = Cross(RSI_Val, 30);
Sell = Cross(70, RSI_Val);
Buy = ExRem(Buy, Sell);
Sell = ExRem(Sell, Buy);

// Chart
Plot(Close, "Price", colorDefault, styleCandle);
PlotShapes(IIf(Buy, shapeUpArrow, shapeNone), colorGreen, 0, Low, -15);
PlotShapes(IIf(Sell, shapeDownArrow, shapeNone), colorRed, 0, High, -15);

_SECTION_END();
'''
